### PR TITLE
fix the missing gmpxx.h issue

### PR DESCRIPTION
**Pull request by robin-thomas**

### CODE REVIEW

**Comment by robin-thomas** [comment]
@prestonvanloon Can you take a look here too?

**Comment by prestonvanloon** [comment]
Hey @robin-thomas, sorry again that buildkite wasn't configured for PRs here.

I've set it up now and pushed the update to the agent and the builds are failing.
They were already failing, but I wanted to make sure this is expected.
Did you expect the build to fail?

**Comment by robin-thomas** [comment]
@prestonvanloon Yes. I was expecting it to fail. Need to update here after the mcl PR was merged.

Give me some time. Let me fix this.

**Review by prestonvanloon — APPROVED** [review]

**Comment by prestonvanloon** [comment]
OK, let me know if you'd like to merge this now or wait for a fix. Thanks!

**Comment by robin-thomas** [comment]
@prestonvanloon Let me try fixing it. m4 issue is tougher to fix here.

**Comment by robin-thomas** [comment]
@prestonvanloon Build has passed!

**Comment by prestonvanloon** [comment]
Yay! OK, let's merge

**Pull request merged**
