### PR TITLE
Fix the issue of build failing second time

### PR DESCRIPTION
**Pull request by robin-thomas**

### CODE REVIEW

**Comment by robin-thomas** [comment]
@prestonvanloon :arrow_up:

**Comment by prestonvanloon** [comment]
It doesn't _fail_ to build a second time, but it is redundantly building still.

`bazel clean; bazel build //...; bazel build //...;`

```
INFO: Invocation ID: 3d09f48e-d9bd-40de-b52d-979d02b14fa8
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
INFO: Invocation ID: 887a0d13-d3d8-403b-b4b1-0410c8bc2b16
INFO: Analysed 4 targets (39 packages loaded, 9953 targets configured).
INFO: Found 4 targets...
INFO: From Compiling external/m4_v1.4.18/lib/c-stack.c [for host]:
external/m4_v1.4.18/lib/c-stack.c:107:1: warning: 'die' defined but not used [-Wunused-function]
 die (int signo)
 ^~~
INFO: Elapsed time: 55.175s, Critical Path: 45.42s
INFO: 695 processes: 693 linux-sandbox, 2 local.
INFO: Build completed successfully, 857 total actions
INFO: Invocation ID: 3c11ec5b-55f1-4022-a377-1ff68f6252f1
INFO: Analysed 4 targets (0 packages loaded, 0 targets configured).
INFO: Found 4 targets...
INFO: Elapsed time: 39.524s, Critical Path: 39.00s
INFO: 4 processes: 2 linux-sandbox, 2 local.
INFO: Build completed successfully, 5 total actions
```

The second build took 40 seconds when it should have loaded the existing build from the first target.

**Comment by robin-thomas** [comment]
@prestonvanloon Actually it's not building again. The 40s is the time it takes to run the configure script (I'm not sure whether it's a Bazel bug, because if I don't run the configure script again, Bazel is unable to find few files because of its sandboxing). After running the script, it matches the output from the previous build. So it takes everything from the cache after that.

**Comment by robin-thomas** [comment]
As for the m4 rule, that's not in my hand. I'm not the one compiling the m4 object files into the binary. I just call the m4 rule.

**Comment by robin-thomas** [comment]
The number of actions in the second build is just 5, but its 577 in the first build. From that alone, it's clear that it's not building everything the second time.

For now, can we merge this?

**Comment by prestonvanloon** [comment]
It’s building the gen headers method. 

I can attach a more detailed output if needed. 

Are you planning to fix the build? I don’t think we’d be able to use this if there are 40 seconds between builds without changes

**Comment by robin-thomas** [comment]
Alright. Let me see whether Bazel allows me to use some loopholes to fix it.

**Comment by robin-thomas** [comment]
@prestonvanloon Can you check again?

**Comment by robin-thomas** [comment]
```
$ bazel test ...
INFO: Invocation ID: 7ef2b5b7-9357-4996-a76a-dad6004fb21e
INFO: Analysed 3 targets (0 packages loaded, 0 targets configured).
INFO: Found 2 targets and 1 test target...
INFO: Elapsed time: 0.990s, Critical Path: 0.04s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
//:go_default_test                                              (cached) PASSED in 0.2s

Executed 0 out of 1 test: 1 test passes.
INFO: Build completed successfully, 1 total action
```

**Review by prestonvanloon — APPROVED** [review]

**Review by prestonvanloon — APPROVED** [review]

**Pull request merged**
